spring:
  application:
    name: domain-service
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        hostname: localhost
        tags: ${spring.application.name}:${spring.cloud.consul.discovery.hostname}
server:
  port: 7070